"""
Pydantic models for YouTube Marketing Agent.

These models define the data structures used throughout the application
for type safety and validation.
"""

from datetime import datetime
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field


class ChannelInfo(BaseModel):
    """Information about a YouTube channel."""

    channel_id: str
    title: str
    description: Optional[str] = None
    subscriber_count: Optional[int] = None
    video_count: Optional[int] = None
    view_count: Optional[int] = None
    thumbnail_url: Optional[str] = None
    custom_url: Optional[str] = None


class VideoData(BaseModel):
    """Raw video data from YouTube API."""

    video_id: str
    title: str
    description: Optional[str] = None
    published_at: datetime
    duration_seconds: int
    view_count: int = 0
    like_count: int = 0
    comment_count: int = 0
    thumbnail_url: Optional[str] = None
    tags: List[str] = Field(default_factory=list)
    category_id: Optional[str] = None

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class VideoKPIs(BaseModel):
    """Calculated KPIs for a video."""

    video_id: str
    title: str
    published_at: datetime
    age_days: float
    duration_seconds: int
    is_short: bool

    # Raw metrics
    views: int
    likes: int
    comments: int

    # Calculated KPIs
    view_velocity: float  # views per day
    like_rate: float  # likes / views
    comment_rate: float  # comments / views
    engagement_score: float  # weighted combination

    # Categorization
    duration_bucket: str  # "short", "medium", "long"

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class FormatCluster(BaseModel):
    """A cluster of videos with similar format/pattern."""

    cluster_id: str
    pattern_name: str
    description: str
    video_count: int

    # Sample videos
    video_ids: List[str]
    sample_titles: List[str] = Field(max_length=5)
    best_video_id: str
    best_video_title: str

    # Aggregate KPIs (median/mean)
    median_views: float
    median_view_velocity: float
    median_like_rate: float
    median_comment_rate: float
    median_engagement_score: float

    # Pattern characteristics
    common_keywords: List[str] = Field(default_factory=list)
    duration_bucket: Optional[str] = None
    avg_duration_seconds: Optional[float] = None


class AnalysisResult(BaseModel):
    """Complete analysis result for a channel."""

    channel_info: ChannelInfo
    analysis_timestamp: datetime = Field(default_factory=datetime.utcnow)

    # Analysis parameters
    videos_analyzed: int
    date_range_start: Optional[datetime] = None
    date_range_end: Optional[datetime] = None

    # Results
    all_videos: List[VideoKPIs]
    top_formats: List[FormatCluster]

    # Recommendations (generated by AI agent)
    recommendations: Optional[str] = None
    quick_wins: Optional[str] = None
    risks_and_limitations: Optional[str] = None

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class AnalysisRequest(BaseModel):
    """Request parameters for YouTube channel analysis."""

    channel_identifier: str  # URL, @handle, or channel_id
    max_videos: int = Field(default=30, ge=1, le=200)
    days_back: Optional[int] = Field(default=None, ge=1, le=365)

    # KPI weights for engagement score
    like_weight: float = Field(default=0.6, ge=0.0, le=1.0)
    comment_weight: float = Field(default=0.4, ge=0.0, le=1.0)

    # Filters
    exclude_keywords: List[str] = Field(default_factory=list)
    min_views: Optional[int] = Field(default=None, ge=0)

    # Marketing context
    marketing_goal: Optional[str] = None
    target_audience: Optional[str] = None
